### ISSUE TITLE
Suggestion: Add new plugins through issues

### ISSUE THREAD

**Issue by tomasbjerre** [jucies/releases#16]
Creating pull requests is very simple. But I think its even more simple to just create an issue.

A Github webhook can trigger on a new issue being created. Trigger a build in Travis.

If issue starts with "Plugin hosting request: name user/repo" then include name user/repo and close issue.

**Comment by bsideup** [comment]
@tomasbjerre PRs are being tested with Travis right now before they merged. Also, there might be some overrides like "tag/version" in properties, so it's not that simple in some cases.

In Jucies I was trying to follow semantic of other repos like CocoaPods, Homebrew, and others, where you can contribute some "formula" to make it available. 

"Create an issue" means that maintainers of Jucies will have to submit such PRs themselves, and original authors will lose visibility of the process. 

Since it's possible to submit PR directly from GitHub, by pressing "New file" at https://github.com/jucies/releases/tree/master/plugins , I think it's simple enough to keep it. 

WDYT?

**Comment by tomasbjerre** [comment]
Yes, just a suggestion =)

**Comment by bsideup** [comment]
@tomasbjerre don't get me wrong - I want it to be as simple as possible, for everyone :) Luckily, process of inclusion in Jucies is one-time operation, and (thanks to GitHub) it's possible to do it from UI only, which is good from my POV :)

**Comment by tomasbjerre** [comment]
No you are probably right =)
